# Generated by Django 4.0.6 on 2022-08-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date']},
        ),
    ]
